#
# snapcraft.yaml - Snapcraft file
# @author Yaroslav Pogrebnyak <yyyaroslav@gmail.com>
#

name: gobetween
version: '1'
version-script: cat VERSION
icon: logo.png
summary: modern & minimalistic load balancer and reverse-proxy for the Cloud era
description: gobetween is free, open-source, modern & minimalistic L4 load balancer and reverse proxy for the Cloud era
confinement: classic
grade: devel
base: core18

parts:
  gobetween:
      plugin: make
      source: .
      source-type: local
      build-packages:
      - golang-go
      - gcc
      - git
      makefile: Makefile
      artifacts:
        - bin/gobetween

  config:
    plugin: dump
    source: .
    stage:
      - config/gobetween.toml

apps:
  gobetween:
    command: bash $SNAP_DATA/gobetween.sh
    daemon: simple
    plugs:
        - network
        - network-bind

